# Generated by Django 4.1.5 on 2023-02-17 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurements_sensor_alter_sensor_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='measurement.sensor'),
        ),
    ]
